// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxppepdwfpofnpimtcvm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4cHBlcGR3ZnBvZm5waW10Y3ZtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyOTI5NjAsImV4cCI6MjA1ODg2ODk2MH0.aSxia8UCSUGmJq1-v_ZeTCXQV2yRxaAQzNLB2mEZpXA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);